// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArzFqfrotVHO8J9vjWpSs0rumd1Eq9aGg',
    appId: '1:360036864400:web:fa09710c1f5d883f51a315',
    messagingSenderId: '360036864400',
    projectId: 'knowaboutsurat-9b0cd',
    authDomain: 'knowaboutsurat-9b0cd.firebaseapp.com',
    storageBucket: 'knowaboutsurat-9b0cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBji0dUaT8waWf4l4-9SqEmBOSzPVfr3DY',
    appId: '1:360036864400:android:68a619d5249ab7e651a315',
    messagingSenderId: '360036864400',
    projectId: 'knowaboutsurat-9b0cd',
    storageBucket: 'knowaboutsurat-9b0cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKu_lXq7H6Vp174rC_LzU5usz8wyW897Y',
    appId: '1:360036864400:ios:c56c8c3c5391163d51a315',
    messagingSenderId: '360036864400',
    projectId: 'knowaboutsurat-9b0cd',
    storageBucket: 'knowaboutsurat-9b0cd.appspot.com',
    iosBundleId: 'com.anycar.knowAboutSurat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKu_lXq7H6Vp174rC_LzU5usz8wyW897Y',
    appId: '1:360036864400:ios:c56c8c3c5391163d51a315',
    messagingSenderId: '360036864400',
    projectId: 'knowaboutsurat-9b0cd',
    storageBucket: 'knowaboutsurat-9b0cd.appspot.com',
    iosBundleId: 'com.anycar.knowAboutSurat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHKlmNqHE_jImsEbVajxPgQ0r4hIdRCws',
    appId: '1:702261236629:web:e81814ac1d0164afcf9c9c',
    messagingSenderId: '702261236629',
    projectId: 'knowaboutsurat',
    authDomain: 'knowaboutsurat.firebaseapp.com',
    storageBucket: 'knowaboutsurat.appspot.com',
  );
}